Ivoz\Cgr\Domain\Model\DestinationRate\DestinationRateAbstract:
  type: mappedSuperclass
  indexes:
    destinationRate_brandId:
      columns:
        - brandId
  uniqueConstraints:
    destinationRate_brandTag:
      columns:
        - tag
        - brandId
  embedded:
    name:
      class: Name
      columnPrefix: false
    description:
      class: Description
      columnPrefix: false
    file:
      class: File
      columnPrefix: false
  fields:
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    status:
      type: string
      nullable: true
      length: 20
      options:
        fixed: false
        comment: '[enum:waiting|inProgress|imported|error]'
        default: 'waiting'
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false