Ivoz\Cgr\Domain\Model\DestinationRate\DestinationRate:
  repositoryClass: Ivoz\Cgr\Infrastructure\Persistence\Doctrine\DestinationRateDoctrineRepository
  type: entity
  table: DestinationRates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks:
    postLoad:
      - initChangelog
  oneToOne:
    tpDestinationRate:
      targetEntity: Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRateInterface
      mappedBy: destinationRate
