Ivoz\Cgr\Domain\Model\TpDestinationRate\Destination:
  type: embeddable
  fields:
    prefix:
      type: string
      nullable: false
      length: 24
      options:
        fixed: false
    prefixName:
      type: string
      nullable: false
      length: 60
      options:
        fixed: false
