Ivoz\Cgr\Domain\Model\TpDestination\TpDestinationAbstract:
  type: mappedSuperclass
  indexes:
    tpDestination_tpid:
      columns:
        - tpid
    tpDestination_tpid_dstid:
      columns:
        - tpid
        - tag
  uniqueConstraints:
    tpid_dest_prefix:
      columns:
        - tpid
        - tag
        - prefix
        - tpDestinationRateId
  fields:
    tpid:
      type: string
      nullable: false
      length: 64
      options:
        fixed: false
        default: 'ivozprovider'
    tag:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    prefix:
      type: string
      nullable: false
      length: 24
      options:
        fixed: false
    name:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    description:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    createdAt:
      type: datetime
      nullable: false
      options:
        default: CURRENT_TIMESTAMP
      column: created_at
  manyToOne:
    tpDestinationRate:
      targetEntity: \Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRateInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        tpDestinationRateId:
          nullable: false
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false