Ivoz\Kam\Domain\Model\TrunksCdr\TrunksCdrAbstract:
  type: mappedSuperclass
  indexes:
    trunksCdr_start_time_idx:
      columns:
        - start_time
    trunksCdr_end_time_idx:
      columns:
        - end_time
    trunksCdr_callid_idx:
      columns:
        - callid
    trunksCdr_xcallid_idx:
      columns:
        - xcallid
    trunksCdr_direction_idx:
      columns:
        - direction
    trunksCdr_cgrid_idx:
      columns:
        - cgrid
  fields:
    startTime:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: start_time
    endTime:
      type: datetime
      nullable: false
      options:
        default: '2000-01-01 00:00:00'
      column: end_time
    duration:
      type: float
      nullable: false
      precision: 10
      scale: 3
      options:
        default: '0.000'
    caller:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    callee:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    referee:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    referrer:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
    callid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    callidHash:
      type: string
      nullable: true
      length: 128
      options:
        fixed: false
      column: callidHash
    xcallid:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    diversion:
      type: string
      nullable: true
      length: 64
      options:
        fixed: false
    bounced:
      type: boolean
      nullable: true
    price:
      type: decimal
      nullable: true
      precision: 10
      scale: 4
    priceDetails:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: priceDetails
    direction:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
    cgrid:
      type: string
      nullable: true
      length: 40
      options:
        fixed: false
      column: cgrid
  manyToOne:
    invoice:
      targetEntity: \Ivoz\Provider\Domain\Model\Invoice\InvoiceInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        invoiceId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    peeringContract:
      targetEntity: \Ivoz\Provider\Domain\Model\PeeringContract\PeeringContractInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        peeringContractId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    destination:
      targetEntity: \Ivoz\Cgr\Domain\Model\TpDestination\TpDestinationInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        destinationId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
    destinationRate:
      targetEntity: \Ivoz\Cgr\Domain\Model\DestinationRate\DestinationRateInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        destinationRateId:
          referencedColumnName: id
          onDelete: set null
      orphanRemoval: false
